### ISSUE TITLE
If shader does not match model, simtoi crashes

### ISSUE THREAD

**Issue by therob762** [bkloppenborg/simtoi#132]
If the user attempts to load a shader that does not match the model (eg. Andrews shader with Pascucci model), SIMTOI crashes.  Perhaps a warning message might be more appropriate.

**Comment by bkloppenborg** [comment]
I cannot replicate this issue. Did you modify the classes and/or shaders? Both the Andrews and Pascucci disk models replace whatever shader is specified in the GUI with the correct shader during construction. Could you run SIMTOI through a debugger (i.e. run `gdb simtoi`) to find where it is crashing?

**Comment by bkloppenborg** [comment]
No reply from reporter in 1 month, cannot replicate issue, closing.
