### ISSUE TITLE
SIMTOI crashing

### ISSUE THREAD

**Issue by therob762** [bkloppenborg/simtoi#145]
After attempts to run multinest on two types of disks (concentric rings, flared disk) with one set of data and a roche rotator with another set of data, SIMTOI yields the same error message:

Error: clCreateFromGLTexture failed. Error code : CL_INVALID_GL_OBJECT
Location : /home/parksj/software/simtoi/lib/liboi/src/liboi.cpp:759
terminate called after throwing an instance of 'std::runtime_error'
  what():  OpenCL error detected.
Aborted (core dumped)

Error continued even after a git pull

**Comment by bkloppenborg** [comment]
The above error indicates that OpenCL can't create a buffer from an OpenGL object. This is likely due to an issue with either your drivers or OpenCL installation.

**Comment by bkloppenborg** [comment]
Following up on this, @therob762 resolved the issue by removing and reinstalling the fglrx drivers on Ubuntu. The issue was outside of SIMTOI.
